/*= ProjectConfiguration.h is autogenerated. Do not Modify =*/

#ifndef ProjectConfigurationOTML_h
#define ProjectConfigurationOTML_h

	#define SKIP_DEBUG_AND_JAILBREAK_SECURITY_CHECK
	#define CERTIFICATE_PINNING_DISABLED
	#define ANTI_SCREEN_RECORDING_DISABLED
	#define LAYOUT_DEBUG_ENABLED (null)
	#define ACCESSIBILITY_IDENTIFIERS_ENABLED

#endif /* ProjectConfigurationOTML_h*/